module.exports = {
firstTitle: [
    'Praetorian',
    'The Gandlock',
    'Fort',
    'Mirage',
    'The Alpine',
    'Central',
    'Fort',
    'Teresterary',
    'Telecom',
    'Redrove',
    'The Upper',
    'The Platinum',
    'Titanium',
    'Dormant',
    'Derelict',
    'The Octic',
    'The Cursive',
    'Hargrid',
    'Carinae',
    'District',
    'District',
    'East',
    'West',
    'North',
    'South',
],

lastTitle: [
    'Bastion',
    'Bulwark',
    'Plataeu',
    'Vigil',
    'Nebulae',
    'Grounds',
    'Course',
    'Orchard',
    'Enclave',
    'Stronghold',
    'Bay',
    'Depot',
    'Storefront',
    'Rift',
    'Mart',
    'Zone 36',
    'Zone 22',
    'Zone 71',
    'Zone 57',
    'Tariff',
    'University',
    'Center',
    'Processing',
    'Refinery',
    'Factory',
    'Establishment',
    'Bankwelt',
    'Front',
],

faction: [
    'Maverine',
    'Maverine',
    'Demotrecon',
    'Demotrecon',
    'Benedict Dominion',
    'Uregeome Union',
    'Galactic Union',
    'Galactic Union',
    'Galactic Union',
    'Sejourn Legion',
    'Avokarl',
    'Hephilus',
    'Hephilus',
    'Solar Legion',
    'Comm League',
    'Independant',
    'Independant',
],

mandates: [
    'No Foreign imports',
    'Locally produced',
    'Internationally produced',
    'Rebreather not required',
    'No Vaccine required',
    'Echo Support',
    'Petro Support',
],

affiliates: [
    'Sacko Enterprise',
    'Medrian Concord',
    'Union',
    'GU Financed',
    'Stockholm Exchange',
    'Union',
    'GU Financed',
    'Sergo Makeshift',
    'Lager Sanctions',
    'Galag Conglomerate',
    'Umbrella Corporation',
    'Umbrella Corporation',
    'UAC',
    'UAC',
    'None',
    'None',
],
}