module.exports = {
  firstTitle: [
    'Praetorian',
    'The Gandlock',
    'Fort',
    'Mirage',
    'The Alpine',
    'Central',
    'Fort',
    'Teresterary',
    'Telecom',
    'Redrove',
    'The Upper',
    'The Platinum',
    'Titanium',
    'Dormant',
    'Derelict',
    'The Octic',
    'The Cursive',
    'Hargrid',
    'Carinae',
    'District',
    'District',
    'East',
    'West',
    'North',
    'South',
  ],

  lastTitle: [
    'Bastion',
    'Bulwark',
    'Plataeu',
    'Vigil',
    'Nebulae',
    'Grounds',
    'Course',
    'Orchard',
    'Enclave',
    'Stronghold',
    'Bay',
    'Depot',
    'Storefront',
    'Rift',
    'Mart',
    'Zone 36',
    'Zone 22',
    'Zone 71',
    'Zone 57',
    'Tariff',
    'University',
    'Center',
    'Processing',
    'Refinery',
    'Factory',
    'Establishment',
    'Bankwelt',
    'Front',
  ],

  owner: [
    'Maverine',
    'Maverine',
    'Demotrecon',
    'Demotrecon',
    'Benedict Dominion',
    'Uregeome Union',
    'Galactic Union',
    'Galactic Union',
    'Galactic Union',
    'Sejourn Legion',
    'Avokarl',
    'Hephilus',
    'Hephilus',
    'Solar Legion',
    'Comm League',
    'Independant',
    'Independant',
  ],

  warnings: [
    'No Foreign imports',
    'Locally produced',
    'Internationally produced',
    'Rebreather not required',
    'No Vaccine required',
    'Echo Support',
    'Petro Support',
  ],

  affiliates: [
  'Government Funded',
  'Non-Profit Organization',
  'Privately Owned',
  'Employee Owned',
  'Stock Company',
  'Conglomerate/International',
  'Locally Operated',
  'Contractor',
  'None',
  'None'
  ],
  industry: [
    'Accounting',
    'Agents',
    'Agriculture',
    'Antiques And Collectables',
    'Arts And Crafts',
    'Asset Management',
    'Automotive',
    'Beverages',
    'Brokers',
    'Business Services',
    'Child Care',
    'Cleaning Services',
    'Construction And Home Improvement',
    'Design',
    'Distributor',
    'Ecommerce',
    'Education And Training',
    'Entertainment',
    'Fashion',
    'Food Services',
    'Gardening And Landscaping',
    'Health And Beauty',
    'Information Technology',
    'Legal Services',
    'Maintenance And Repair',
    'Management Services',
    'Manufacturing',
    'Marketing Services',
    'Media',
    'Medical Practitioners',
    'Music',
    'Nightlife',
    'Personal Services',
    'Pet Services',
    'Photography',
    'Professional Services',
    'Publishing',
    'Recruiting And Staffing',
    'Rental And Leasing',
    'Research Services',
    'Retail',
    'Shipping And Delivery',
    'Sports And Recreation',
    'Sustainability',
    'Toys And Hobbies',
    'Transportation',
    'Travel And Tourism',
    'Value Added Reseller',
    'Warehousing And Storage',
    'Wholesale',
    'Business Services',
    'Fashion',
    'Media',
    'Retail',
    'Value Added Reseller',
    'Small Business Risk',
    'Ecommerce Examples',
    'Promotion Strategy',
    'Business Costs',
    'Entrepreneur Definition',
    'Micromarketing',
    'Local Marketing',
    'Business Name',
    'Business Competition',
    'Marketing',
    'Branding Guide',
    'Marketing Metrics',
    'Pricing Strategy',
    'Product Positioning',
    'Brand Storytelling',
    'Cross-Selling',
    'Marketing Campaign',
    'Marketing Automation',
    'Target Marketing',
    'Trending'
  ],
}
